name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "**.py"
  pull_request:
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment for 3.11
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nox

      # Step 4: Run nox sessions
      - name: Running Linters
        run: nox -s lint

      - name: Building wheel
        run: nox -s build

      - name: Create .env file
        run: |
          touch.env
          echo DB_TYPE="sqlite" >> .env
          echo MEMORY="True" >> .env
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          echo ALGORITHM="HS256"
          echo ACCESS_TOKEN_EXPIRE_MINUTES=30

      - name: Running tests
        run: nox -s test
